version: '3.5'

networks:
  selenoid:
    name: selenoid


services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:1.10.1
    volumes:
      - ./configs:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reports/video/:/opt/selenoid/video
      - ./reports/logs/:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/reports/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
